### ISSUE TITLE
Serialization fails to compile with gcc-6.3 due to -Werror=overloaded-virtual on operator=()

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#164]
Took me quite a while to figure out what's happening here.  When compiling on a 17.04 container, which has gcc-6.3, derived classes like BlockMatrix etc., are giving errors such as:

~~~
/root/siconos/io/src/RegisterModelIbin.cpp:36:32:   required from here
/root/siconos/kernel/src/utils/SiconosAlgebra/BlockMatrix.hpp:414:18: error: 'virtual SiconosMatrix& BlockMatrix::operator=(const DenseMat&)' was hidden [-Werror=overloaded-virtu\
al]
   SiconosMatrix& operator = (const DenseMat& m);
                  ^~~~~~~~
/root/siconos/kernel/src/utils/SiconosAlgebra/BlockMatrix.hpp:402:18: error: 'virtual SiconosMatrix& BlockMatrix::operator=(const SiconosMatrix&)' was hidden [-Werror=overloaded-\
virtual]
   SiconosMatrix& operator = (const SiconosMatrix& m);
                  ^~~~~~~~
~~~

due to the `-Werror-overloaded-virtual` flag.  After following the breadcrumbs, the error comes from `register_type` in boost::serialize.  It turns out that this function returns a "singleton wrapper" object which is a class derived from the templated class.  However, in C++ the *non-virtual* operator=() is automatically derived during inheritance if it is not specified, and "hides" virtual functions in the base class.  I don't see a way around it, I think without being able to change boost::serialize, we must turn off this error for io if WITH_SERIALISATION=ON.

Or maybe there is a way to do this other than using `register_type`?  https://stackoverflow.com/questions/12707500/boost-serialization-and-register-type/12782754

**Comment by radarsat1** [comment]
Of course this only happens in DEV_MODE.  I will turn off the flag for now, as it is not really likely we will mess with the whole serialization scheme right now.  I did try adding an "ignore" pragma to the register_type section of SiconosFullGenerated.hpp and SiconosFullKernelGenerated.hpp but it didn't make the error go away.  (Gcc doesn't have a great record of respecting ignore pragmas I guess..)
