### ISSUE TITLE
recent openblas changes, can't compile on ubuntu 17.04

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#182]
I recently updated to push the change I was working on regarding removing DS from the graph.

However, now I can't compile and it seems to be related to the recent changes regarding OpenBLAS.  Interestingly in the docker container I use for testing which runs Ubuntu 14.04 it compiled and ran tests without problems.

~~~
/home/sinclairs/projects/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/\
level1/dotc.hpp: In function ‘std::complex<float> boost::numeric::bindings::blas::detail\
::dotc(int, const std::complex<float>*, int, const std::complex<float>*, int)’:          
/home/sinclairs/projects/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/\
level1/dotc.hpp:67:97: error: ‘openblas_complex_float’ does not name a type              
     cblas_cdotc_sub( n, OPENBLAS_CONST_FLOAT_CAST(x), incx, OPENBLAS_CONST_FLOAT_CAST(y\
), incy, OPENBLAS_OPENBLAS_COMPLEX_FLOAT_CAST(&result) );                                
                                                                                        \
         ^                                               
~~~

.. and more like that.
Should I install something / set some flag?  Sorry, I don't know anything about OpenBLAS or I would try to debug it further.

**Comment by fperignon** [comment]
HI, 

first of all, try to completely clean your build/install. It is supposed to work properly on ubuntu (at least …)
If it stills fail, check the output during cmake run concerning blas and lapack libs and headers and tell us.

**Comment by vacary** [comment]
Unfortunately, standard BLAS and OpenBlas do not have the same signature. BLAS is typeless (void* ) and OpenBLAS has types. see the discussion there:
https://bitbucket.org/blaze-lib/blaze/issues/50/cannot-convert-const-std-complex-to-const

Do yo have openblas installed on your ubuntu 17.04 ?

To adapt the numeric bindings embedded in Siconos, I adapted the call to Openblas with a macro at line 19 in
https://github.com/siconos/siconos/blob/master/externals/numeric_bindings/boost/numeric/bindings/blas/detail/cblas.h

But it seems that something is wrong on some linuxes. On Fedora, we get the same error as you. It seems that we are not including the correct cblas.h that comes from openblas but the cblas.h that comes from our own implementation.

**Comment by radarsat1** [comment]
I was doing this at the end of the day yesterday, it may just be that I needed to clean better, I'll update after a more thorough investigation.

**Comment by bremond** [comment]
siconos does not compile anymore on ubuntu/openblas:

http://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=27219

probably @radarsat1 you are in this situation.

For the moment, a quick work around is to use atlas-lapack instead :

sudo apt-get remove liblapacke-dev liblapacke libopenblas-base libopenblas-dev

sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev libatlas-dev

**Comment by radarsat1** [comment]
Indeed, I was just about to post that I discovered that my containers didn't have openblas installed, and indeed it compiles for me if I do `apt-get remove libopenblas-dev`.  Thanks!

**Comment by radarsat1** [comment]
Now that I have the problem nicely isolated to a container maybe I can help debug ;)  It's just a missing type, so probably a missing #include somewhere.

**Comment by radarsat1** [comment]
I fixed it here by inserting the following #include in cblas.h:

~~~
#ifdef HAS_OpenBLAS
#include <openblas/openblas_config.h>
#define OPENBLAS_CONST_FLOAT_CAST(x) reinterpret_cast<const float*>(x)
#define OPENBLAS_CONST_DOUBLE_CAST(x) reinterpret_cast<const double*>(x)
~~~

Seeing as this is the only place in the source that uses the HAS_OpenBLAS flag, I suppose this might be an okay place to put this.  Shall I commit it?

**Comment by radarsat1** [comment]
Or maybe we need to first check for the existence of openblas_config.h. Is it standard and present on all openblas installations, or is it something debian/ubuntu specific?

**Comment by bremond** [comment]
In order to try to understand from the beginning, in my local source I have reverted ef2b67803

An I had openblas as hint dir in FindBlas.cmake


diff --git a/cmake/FindBLAS.cmake b/cmake/FindBLAS.cmake
index 82da06f5d..68abade43 100755
--- a/cmake/FindBLAS.cmake
+++ b/cmake/FindBLAS.cmake
@@ -248,7 +248,7 @@ if(NOT BLAS_FOUND)
       # to ensure that std::complex<double> can be casted to double* and produces good results we should enfore std=c++11
       # Right now openblas ships with a cblas.h header which uses double* as type for pointer to double complex, which makes ublas cry since it
       # want to pass std::complex<double>*
-      set(BLAS_INCLUDE_SUFFIXES cblas_header)
+      set(BLAS_INCLUDE_SUFFIXES openblas)
       set(INCLUDE_DIR_HINTS ${CMAKE_SOURCE_DIR}/externals/blas_lapack)
     endif(BLAS_LIBRARIES)
   endif()


This does not compile and in /usr/include/openblas/cblas.h one can see
for example

float  cblas_scasum(OPENBLAS_CONST blasint n, OPENBLAS_CONST float  *x, OPENBLAS_CONST blasint incx);

the vector *x should be single precision complex.


This is really an issue with the installation of openblas and not the
fault of boost bindings.

Finally I think than what @xhub did in
d28d3ca1be273094bb3eb06a826b357c71c01afd is *much better* than patching
generated boost bindings as in ef2b67803

And then we should rather understand why on mac os x and nix the header cblas.h was
probably not the correct one. This is probably because cblas.h in this
case is located in a directory which is find by FindBlas.cmake. And this
means that FindBlas.cmake in the case of openblas should *always* return
the version located in externals/blas_lapack/cblas_header/cblas.h

**Comment by vacary** [comment]
openblas_config.h is a standard file of OpenBLAS and it should be included trough the cblas.h delivered by the OpenBLAS.

The problem we have on Fedora and Ubuntu is the fact cblas.h in installed in /something/include/openblas and we are not able to find it. In that case, we replace it by our own cblas.h. This tricks has been done to fis a bug in old debian that were not distributed cblas.h

To fix the bug when we use OpenBlAS, we need to search for the correct cblas.h in  /something/include/openblas in FindBLAS.cmake

**Comment by bremond** [comment]
@vacary: there is an issue with openblas/cblas.h (at least for  < c++11). The problem on nix was that this incorrect cblas.h was found by FindBlas.cmake while it was not found on fedora and ubuntu. I really think that we should not use this file until we switch defintively to c++11. I propose a revert on your commit ef2b678 with just a mandatory use of the provided cblas.h under externals in #183 This is ok for me on ubuntu 17.04, I did not check on nix yet...

**Comment by vacary** [comment]
@bremond In the meantime, I committed 2aff11df019a534e9621c65a24c94ebdd96c8a20 a fix that uses the cblas.h from openblas/cblas.h in OpenBlas is used. It works on Ubuntu. Let us see on Fedora.

We have to choose one of the option
- using open/cblas.h when openblas is used. I have no issue on my side with  < c++11.
- using our own home cblas.h with the risk that it will not fit with the OpenBlas lib. On nix, it will not work since cblas.h of openblas is directly into standard include dir

**Comment by vacary** [comment]
@bremond We are editing the issue and the file at the same time :-)

it seems that our cblas.h in ${CMAKE_SOURCE_DIR}/externals/blas_lapack does not solve the problem on nix. curious ?

https://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=27257

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2017-08-30 09:39:43 -0700]:

> @bremond We are editing the issue and the file at the same time :-)
> 
> it seems that our cblas.h in ${CMAKE_SOURCE_DIR}/externals/blas_lapack does not solve the problem on nix. curious ?
> 
> https://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=27257

The function signature for cblas_scasum is not the same as in
${CMAKE_SOURCE_DIR}/externals/blas_lapack:

float  cblas_scasum(const int N, const void *X, const int incX)
vs
float cblas_scasum(blasint, const float*, blasint)

This means that the cblas.h that is included is not the one in ${CMAKE_SOURCE_DIR}/externals/blas_lapack
My guess is that it is due to the include order, but I can't see why

**Comment by radarsat1** [comment]
The last change on master doesn't seem to work, but I just tested #183 and it seems to compile fully.

**Comment by vacary** [comment]
@radarsat1 could you explain why the last change on master is not compiling on your computer ?

Cdash https://cdash-bipop.inrialpes.fr/index.php?project=Siconos reports that it compiles on ubuntu debian and Fedora.

**Comment by radarsat1** [comment]
Just tried it in a fresh container after `apt-get install libopenblas-dev`, and this is the first error I get:

```
[ 53%] Building CXX object kernel/CMakeFiles/kernel.dir/src/utils/SiconosAlgebra/SimpleMatrix.cpp.o
In file included from /root/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/level1/asum.hpp:38:0,
                 from /root/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/level1.hpp:15, 
                 from /root/siconos/externals/numeric_bindings/boost/numeric/bindings/blas.hpp:12,
                 from /root/siconos/kernel/src/utils/SiconosAlgebra/SimpleMatrix.cpp:38:
/root/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/level1/dotc.hpp: In function 'std::complex<float> boost::numeric::bindings::blas::detail::dotc(int, const std::complex<float>*, int, const std::complex<float>*, int)':
/root/siconos/externals/numeric_bindings/boost/numeric/bindings/blas/level1/dotc.hpp:67:97: error: expected type-specifier before 'openblas_complex_float'
     cblas_cdotc_sub( n, OPENBLAS_CONST_FLOAT_CAST(x), incx, OPENBLAS_CONST_FLOAT_CAST(y), incy, OPENBLAS_OPENBLAS_COMPLEX_FLOAT_CAST(&result) );
                                                                                                 ^
```

I'll try to see what the difference is with cdash, it may be because the container also has other lapack/blas packages installed.

**Comment by radarsat1** [comment]
Okay I was unable to find a package in 17.04 that I could remove that makes it work while libopenblas-dev is installed, always the same error.  However, I found that on 16.04, after installing libopenblas-dev, it does in fact compile.  I will try to figure out the difference.

**Comment by radarsat1** [comment]
Well, I guess I'm confused.  I started my 17.04 container again from scratch, installed libopenblas-dev, and am no longer getting the error. I'll close this, and re-open if I can reproduce the problem again, but perhaps it is solved.
