### ISSUE TITLE
Occ swig wrapper fails to compile

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#295]
When building mechanisms, occ swig wrapper fails to compile with pythonocc-core 0.18.1 and one 0.18.1.
```
/scratch/Vincent/Build/siconos/release_with_mechanisms/wrap/siconos/mechanics/occPYTHON_wrap.cxx:28794:39: error: 
      use of undeclared identifier 'SWIGTYPE_p_std11__shared_ptrT_TopoDS_Shape_t'
    res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_std11__shared_ptrT_TopoDS_Shape_t, 0);
```

The main reason is due to a mix in shared pointer between std11 and siconos shares pointer when generating the swig interface :

```
  if (argc == 0) {
    return _wrap_new_OccContactShape__SWIG_0(self, args);
  }
  if (argc == 1) {
    int _v;
    int res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_std__shared_ptrT_TopoDS_Shape_t, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      return _wrap_new_OccContactShape__SWIG_1(self, args);
    }
  }
  if (argc == 1) {
    int _v;
    int res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_std__shared_ptrT_OccContactShape_t, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      return _wrap_new_OccContactShape__SWIG_3(self, args);
    }
  }
  if (argc == 1) {
    int _v;
    
    int res;
    res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_std11__shared_ptrT_TopoDS_Shape_t, 0);
    _v = SWIG_CheckState(res);
    if(!_v)
    {
      /* this might be the case if the pointer comes directly from pythonocc */
      res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_TopoDS_Shape, 0);
      _v = SWIG_CheckState(res);
      if(!_v)
      {
        res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_TopoDS_Compound, 0);
      }
    }
    _v = SWIG_CheckState(res);
    
    if (_v) {
      return _wrap_new_OccContactShape__SWIG_2(self, args);
    }
  }
```

**Comment by vacary** [comment]
Using 	-DCMAKE_CXX_STANDARD=11  in the campe options fix the bug.

Once again, I think we have to force this option

**Comment by fperignon** [comment]
For Siconos it’s already like this in the main CMakeLists.txt :

set(CMAKE_CXX_STANDARD 11)

you’re talking about compilation of OCE ?

**Comment by vacary** [comment]
No, I m talking about the compilation of siconos

In fact it partly works. I continue to try to find a fix
