### ISSUE TITLE
Compilation and installation MacOsX Catalina

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#346]
I experienced some issues for the compilation and the installation on MacOsX Catalina (10.15)

For BLAS/LAPACK, I used the Accelerate Framework by installing Xcode and the commandline tools:
``` 
xcode-select --install
```

Blas is correctly detected, but the compilation is failing due to a recent change in Cmake.  It doesn't work with make 3.18.2 but it works well with make 3.16.3. I have to downgrade. It seems related to the `isystem` and `isysroot` options of the clang compiler.

For Python, I used python 3.8 installed with macport and then pip for the installation of python packages (packaging, NumPy, scipy,  lxml ). For the other dependencies (fortran, boost, ...), I used macport. 

The compilation is working well

**Comment by vacary** [comment]
For the installation, I have a problem with the installation of the python modules.

With my versions of NumPy 1.19 and packaging 1.15.0, the script `siconos/warp/setup.py.in` has a problem.

```
from numpy.distutils.core import setup, Extension, Command
>>> from numpy.distutils.core import setup, Extension, Command
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Command' from 'numpy.distutils.core' (/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/distutils/core.py)
```

It seems that `Command` is no longer a class of the module `numpy.distutils.core`

**Comment by vacary** [comment]
@fperignon Thank you.

The commit d27d706 fixes the problem with new CMake (works fro 3.18.2) and the installation problem with Command in NumPy.distutils.core.

By the way, NumPy.distutils.core and distutils.core are both necessary ?
